#!/bin/bash
##
#   Read saved BunsenLabs Conky session file(s) and start the conkys
#
#   written by <damo> for BunsenLabs, April 2015
#
########################################################################
CONKYPATH="$HOME/.conky"
SESSIONFILE="$CONKYPATH/conky-session"
USAGE=$(echo -e "\v  USAGE: with no command argument, the script uses the default"
    echo -e "\t conky session file '$SESSIONFILE'\v"
    echo -e "  To run other session files use:\v"
    echo -e "\t'bl-conky-session /path/to/file1 /path/to/file2 etc'\v")
    
findArgs(){     # get command args (sessionfile paths)
    i=0

    for arg in "$@";do
        if [[ $arg = "default" ]];then
            arg="$SESSIONFILE"
        fi
        if test -f  "$arg" &>/dev/null;then # sessionfile exists
            rawArr[$i]="$arg"       # add sessionfiles to array
            i=$(($i+1))
        else
            echo $"ERROR: $arg not found" >&2
            exit 1
        fi
    done
    # remove duplicate args
    sessArr=(`printf "%s\n" "${rawArr[@]}" | sort -u`)
    killConkys
    for session in "${sessArr[@]}";do # run the conkys in the sessionfiles
        source "$session"
    done
}

killConkys(){
    msg="Kill running conkys first?"
    RET=$(zenity --question --text="$msg")
    if [[ $? == 0 ]];then            # kill all conkys
        if [ "$(pidof conky)" ];then
            killall conky && sleep 0.2s
        fi
    fi
}

if [ $# -eq 0 ];then    # if no args, then run default sessionfile
    killConkys
    source $SESSIONFILE
elif [[ $1 = "-h" ]] || [[ $1 = "--help" ]];then
    echo "$USAGE"
    exit 0
else 
    findArgs $@    # get the sessionfile paths from the command args
fi

exit 0
