#!/bin/bash
##
#   Read a saved BunsenLabs Conky session file and start the conkys
#
#   written by <damo> for BunsenLabs, April 2015
#
########################################################################
CONKYPATH="$HOME/.conky"

if [ $# -eq 0 ];then
    SESSIONFILE="$CONKYPATH/conky-session.txt"
elif [[ $1 = "-h" ]] || [[ $1 = "--help" ]];then
    echo "  USAGE: with no command argument, the script uses the default"
    echo "  conky session file '$CONKYPATH/conky-session.txt'"
    echo
    echo "  To run other session files use 'bl-conky-session /path/to/file'"
    echo
    exit 0
else
    SESSIONFILE="$1"
fi

if [ -e "$SESSIONFILE" ];then
   source $SESSIONFILE
else
    echo $"ERROR: $SESSIONFILE not found" >&2
    exit 1
fi

exit 0
