#!/bin/bash
##
#   Read a saved BunsenLabs Conky session file and start the conkys
#
#   written by <damo> for BunsenLabs, April 2015
#
########################################################################
CONKYPATH=".conky"
SESSIONFILE="$CONKYPATH/conky-session.txt"

if [ -e "$SESSIONFILE" ];then
   source $SESSIONFILE
else
    echo $"ERROR: $SESSIONFILE not found" >&2
    exit 1
fi

exit
