#!/bin/bash
##
#   Read a saved BunsenLabs tint2 session file and start the tint2s
#
#   written by <damo> for BunsenLabs, April 2015
#
########################################################################
TINT2PATH="$HOME/.config/tint2"

if [ $# -eq 0 ];then
    SESSIONFILE="$TINT2PATH/tint2-session.txt"
elif [[ $1 = "-h" ]] || [[ $1 = "--help" ]];then
    echo "  USAGE: with no command argument, the script uses the default"
    echo "  Tint2 session file '$TINT2PATH/tint2-session.txt'"
    echo
    echo "  To run other session files use 'bl-tint2-session /path/to/file'"
    echo
    exit 0
else
    SESSIONFILE="$1"
fi

if [ -e "$SESSIONFILE" ];then
   source $SESSIONFILE
else
    echo $"ERROR: $SESSIONFILE not found" >&2
    exit 1
fi

exit 0
